version: '3.8'
services:
  user-service:
    build: .
    image: user-service:latest
    ports:
      - '3010:3000'
    networks:
      - my-network
    depends_on:
      - mongouser

  mongouser:
    image: mongo:latest
    ports:
      - '27018:27017'
    networks:
      - my-network
    environment:
      MONGO_INITDB_DATABASE: user-service
    volumes:
      - mongodb-data:/data/db

networks:
  my-network:
    driver: bridge

volumes:
  mongodb-data:
